import os
from Bio import SeqIO

##### Configuration #####

config["analysis_stem"]=[i for i in config["analysis_stem"].split(',')]

##### Target rules #####

rule all:
    input:
        expand(config["output_path"] + "/consensus_sequences/{sample}.fasta",sample=config["sample"]),
        expand(config["output_path"] + "/reports/{sample}.report.md",sample=config["sample"])

##### Modules #####
include: "rules/map_polish.smk"


